/* ============================================================
   Customer Shopping Behavior — Analysis Queries (T-SQL / SSMS)
   Replace dbo.CustomerShoppingBehavior with your actual table name
   ============================================================ */

-- Q1. Total revenue generated by male vs. female customers
SELECT
    Gender,
    SUM([Purchase Amount (USD)]) AS TotalRevenue
FROM dbo.CustomerShoppingBehavior
GROUP BY Gender;


-- Q2. Customers who used a discount but still spent more than the average purchase amount
SELECT *
FROM dbo.CustomerShoppingBehavior
WHERE [Discount Applied] = 'Yes'
  AND [Purchase Amount (USD)] > (
        SELECT AVG([Purchase Amount (USD)])
        FROM dbo.CustomerShoppingBehavior
      );


-- Q3. Top 5 products with the highest average review rating
SELECT TOP 5
    [Item Purchased],
    AVG([Review Rating]) AS AvgRating
FROM dbo.CustomerShoppingBehavior
GROUP BY [Item Purchased]
ORDER BY AvgRating DESC;


-- Q4. Compare average Purchase Amounts between Standard and Express Shipping
SELECT
    [Shipping Type],
    AVG([Purchase Amount (USD)]) AS AvgPurchaseAmount
FROM dbo.CustomerShoppingBehavior
WHERE [Shipping Type] IN ('Standard', 'Express')
GROUP BY [Shipping Type];


-- Q5. Do subscribed customers spend more? Compare avg spend and total revenue
SELECT
    [Subscription Status],
    AVG([Purchase Amount (USD)]) AS AvgSpend,
    SUM([Purchase Amount (USD)]) AS TotalRevenue
FROM dbo.CustomerShoppingBehavior
GROUP BY [Subscription Status];


-- Q6. Top 5 products with the highest percentage of purchases with discounts applied
SELECT TOP 5
    [Item Purchased],
    SUM(CASE WHEN [Discount Applied] = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*) AS DiscountPct
FROM dbo.CustomerShoppingBehavior
GROUP BY [Item Purchased]
ORDER BY DiscountPct DESC;


-- Q7. Segment customers into New, Returning, Loyal based on Previous Purchases
SELECT
    CASE
        WHEN [Previous Purchases] <= 5              THEN 'New'
        WHEN [Previous Purchases] BETWEEN 6 AND 20   THEN 'Returning'
        ELSE 'Loyal'
    END AS CustomerSegment,
    COUNT(*) AS CustomerCount
FROM dbo.CustomerShoppingBehavior
GROUP BY
    CASE
        WHEN [Previous Purchases] <= 5              THEN 'New'
        WHEN [Previous Purchases] BETWEEN 6 AND 20   THEN 'Returning'
        ELSE 'Loyal'
    END;


-- Q8. Top 3 most purchased products within each category
WITH ProductCounts AS (
    SELECT
        Category,
        [Item Purchased],
        COUNT(*) AS PurchaseCount
    FROM dbo.CustomerShoppingBehavior
    GROUP BY Category, [Item Purchased]
),
Ranked AS (
    SELECT
        Category,
        [Item Purchased],
        PurchaseCount,
        ROW_NUMBER() OVER (PARTITION BY Category ORDER BY PurchaseCount DESC) AS rn
    FROM ProductCounts
)
SELECT Category, [Item Purchased], PurchaseCount
FROM Ranked
WHERE rn <= 3
ORDER BY Category, PurchaseCount DESC;


-- Q9. Are repeat buyers (more than 5 previous purchases) also more likely to subscribe?
SELECT
    CASE WHEN [Previous Purchases] > 5 THEN 'Repeat Buyer' ELSE 'New/Low-Activity Buyer' END AS BuyerType,
    [Subscription Status],
    COUNT(*) AS CustomerCount
FROM dbo.CustomerShoppingBehavior
GROUP BY
    CASE WHEN [Previous Purchases] > 5 THEN 'Repeat Buyer' ELSE 'New/Low-Activity Buyer' END,
    [Subscription Status]
ORDER BY BuyerType, [Subscription Status];


-- Q10. Revenue contribution of each age group
SELECT
    CASE
        WHEN Age BETWEEN 18 AND 25 THEN '18-25'
        WHEN Age BETWEEN 26 AND 35 THEN '26-35'
        WHEN Age BETWEEN 36 AND 45 THEN '36-45'
        WHEN Age BETWEEN 46 AND 55 THEN '46-55'
        WHEN Age BETWEEN 56 AND 65 THEN '56-65'
        ELSE '66+'
    END AS AgeGroup,
    SUM([Purchase Amount (USD)]) AS TotalRevenue,
    SUM([Purchase Amount (USD)]) * 100.0 / SUM(SUM([Purchase Amount (USD)])) OVER () AS RevenuePct
FROM dbo.CustomerShoppingBehavior
GROUP BY
    CASE
        WHEN Age BETWEEN 18 AND 25 THEN '18-25'
        WHEN Age BETWEEN 26 AND 35 THEN '26-35'
        WHEN Age BETWEEN 36 AND 45 THEN '36-45'
        WHEN Age BETWEEN 46 AND 55 THEN '46-55'
        WHEN Age BETWEEN 56 AND 65 THEN '56-65'
        ELSE '66+'
    END
ORDER BY AgeGroup;
